# Generated by Django 4.0 on 2021-12-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_booking_outboundleg_remove_booking_returnleg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundleg',
            name='segments',
        ),
        migrations.AddField(
            model_name='outboundleg',
            name='segments',
            field=models.ForeignKey(default='lol', on_delete=django.db.models.deletion.CASCADE, to='home.segment'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='returnleg',
            name='segments',
        ),
        migrations.AddField(
            model_name='returnleg',
            name='segments',
            field=models.ForeignKey(default='lol', on_delete=django.db.models.deletion.CASCADE, to='home.segment'),
            preserve_default=False,
        ),
    ]
