# Generated by Django 4.0 on 2021-12-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_outboundleg_segments_outboundleg_segments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outboundleg',
            name='segments',
        ),
        migrations.AddField(
            model_name='outboundleg',
            name='segments',
            field=models.ManyToManyField(to='home.Segment'),
        ),
        migrations.RemoveField(
            model_name='returnleg',
            name='segments',
        ),
        migrations.AddField(
            model_name='returnleg',
            name='segments',
            field=models.ManyToManyField(to='home.Segment'),
        ),
    ]
